# Build
FROM docker.io/library/node:22-alpine AS builder
COPY . /app
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
ENV CI=true
ENV VITE_BASE=/
RUN pnpm install --frozen-lockfile
RUN pnpm run build

FROM docker.io/nginx:stable-alpine3.23-perl
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
