# Build
FROM docker.io/library/node:22-alpine AS builder
COPY . /app
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
RUN pnpm run build

FROM docker.io/library/node:22-alpine
RUN corepack enable
COPY ./package.json pnpm-lock.yaml /app/
# COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/dist /app/build
WORKDIR /app
RUN pnpm install --prod --frozen-lockfile
EXPOSE 3000
CMD ["pnpm", "run", "start"]